### ISSUE TITLE
Cannot compile template on IE8, IE7

### ISSUE THREAD

**Issue by Thinkscape** [BorisMoore/jsrender#128]
``` js
// Under IE7 and IE8
String.prototype.whatever = function(){}; 
$.views.templates({foo:'whatever with a var {{:var}}'}); 
$.render.foo({var:'foo'}); // throws "Expected identifier, string or number" 
```

String prototype is often extended in JS apps to add missing ECMA5 features, such as `String.trim()` or `Array.indexOf`. After extending string prototype in IE7, when building the template, that extra function definition is concat together with string from data.

**Comment by Wancieho** [comment]
Ye im bringing this back from the land of the dead but @Thinkscape you need to tell me who your dealer is cause u are/were on some serious sh1t. Who even uses reserved words/syntax in their code besides its real purpose and then still complains? Maybe since posting this you realised the ridiculousness in your argument.
