### ISSUE TITLE
Option to not escape embedded HTML

### ISSUE THREAD

**Issue by miguelmartinez0** [BorisMoore/jsrender#172]
Is there an option to render embed HTML UN-escaped? For example I have the following string: "hello, my name is <strong>Miguel</strong>". I expect to see "Miguel" in bold.

Thank you,
Miguel
miguel@miguelmartinez.com

**Comment by larjohn** [comment]
I am trying to render a report generated by dynamicreports (a Java reporting library)
This line 
error('Parent of <tr> must be <tbody>')

causes the rendering to stop. I can't really modify dynamicreports in order to. 

Is there a way to avoid validation and let the browser be responsible for it?

**Comment by BorisMoore** [comment]
Unfortunately, if you are using JsViews (link method) and you have  `<table><tr><td>...</td></tr></table>`  and you use data-link attributes or {^{...}} tags on or within that content, then behavior can be unpredictable, since browsers may or may not dynamically insert a body tag. So the nesting depth of elements and the results of stepping through will be different at the time of linking than it was at the time of rendering.

If you are using the render method - not doing data-linking, you will not get the error message. But if you are linking, you will - and this validation does need to be done by JsViews, not just by the browser...

**Comment by BorisMoore** [comment]
That said, I will consider changing the code for the next update, so that by setting `$.views.settings.noValidate = true;` you can opt out of this validation. But in that case, depending on how you use data-linking within the invalid content, you may or not get other bugs occuring.

**Comment by BorisMoore** [comment]
@larjohn: I have included this in the latest update. By setting $.views.settings.noValidate = true; you can opt out of the <tbody> validation.
