### ISSUE TITLE
PHP function and json variable in jsrender template

### ISSUE THREAD

**Issue by anto2b** [BorisMoore/jsrender#254]
I would like to include php function in jsRender template like this :

<li><?php echo my_function('{{:number}}'); ?></li>

but display only the string of caracters "{{:number}}" and not the expected value returned by the PHP function.

However when I run the following code
<li><?php echo'{{:number}}'; ?></li>
It's work and display the expected value to {{number}} !

Do you have a solution for me with this problem? Thank you in advance !

**Comment by BorisMoore** [comment]
It looks like this is a problem with the processing model of PHP and how that integrates with JsRender in your environment. It's not a JsRender issue as such, and is not possible to answer here, since there are too many unknowns about the order of processing etc. between PHP and the JsRender render() call.
