### ISSUE TITLE
No {{for}}-#index when wrapped in {{if}}

### ISSUE THREAD

**Issue by omelhoro** [BorisMoore/jsrender#255]
var data=["foo","","bar"]

    <div> {{for data}}
        {{if #data}}
        <span data-ix={{:#index}} >{{:#data}}
        </span>
        {{else}}
        <p></p>
        {{/if}}
        {{/for}}
     </div>

when rendered it leaves data-ix empty. Using 1.0

**Comment by BorisMoore** [comment]
Use `<span data-ix="{{:#getIndex()}}" >`

I'm not sure what you mean by using 1.0. JsRender is beta.

If you use recent versions, and if you include quotes around your attribute: `<span data-ix="{{:#index}}" >` you should have got 

`<span data-ix="Unavailable (nested view): use #getIndex()" >foo</span>`

which documents the fact that in nested views, you should use `<span data-ix="{{:#getIndex()}}" >` rather than `<span data-ix="{{:#index}}" >`

See: https://github.com/BorisMoore/jsrender/issues/173#issuecomment-11216255

(BTW it is always best to search previous issues for dups - there are several that address #index in nested {{if}} etc...)

**Comment by omelhoro** [comment]
Thanks, I guess that was a beginners error not to look for previous issues))

**Comment by BorisMoore** [comment]
NP!
