### ISSUE TITLE
Request for search feature in documentation

### ISSUE THREAD

**Issue by jagandecapri** [BorisMoore/jsrender#274]
Hello @BorisMoore, first of all, you have done an awesome library. :100: 

As a suggestion, it would be great if there is a search feature in the documentation to search through
the APIs.

Cheers.

**Comment by BorisMoore** [comment]
Yes, totally agree, a search feature would help a lot - and is planned.

Actually that is an issue for the https://github.com/BorisMoore/jsviews.com project, and indeed there is already that issue filed: here https://github.com/BorisMoore/jsviews.com/issues/2.

I'm not sure how soon I'll be able to add the search, since priority now is getting the basic docs complete, then publishing the official V1 of both JsRender and JsViews.

Closing this issue.

**Comment by jagandecapri** [comment]
Thanks for the clarification @BorisMoore :+1:

**Comment by BorisMoore** [comment]
www.jsviews.com does now have a powerful search feature.

Here is an example: http://www.jsviews.com/#search?s=%24.templates(

**Comment by jagandecapri** [comment]
Awesome!!!
