### ISSUE TITLE
Cannot find helper with `$.views.helpers(name, helper)`

### ISSUE THREAD

**Issue by mosquito1994** [BorisMoore/jsrender#303]
Hello here I got a problem with helper while rendering a template. I use `$.views.helpers("name", helper)` firstly and then render my page with `$.render.test(data, name)` (test is name for the template and data for the data injected), however I get an error says "name is not defined". 

What's more, when I use `var name = $.views.helpers(helper) ` and then render the page, it works.

`$.templates("name", template)` works well here but  `$.views.helpers("name", helper)` dosen't. Could you please help me on the reason why such a thing happens?

**Comment by BorisMoore** [comment]
Did you see the overview here: http://www.jsviews.com/#helpers?

`$.views.helpers("myHlp", myhelper)` will register your `myhelper` helper under the name ``"myHlp", so that **_in a template_** you can access it as in `{{:~myHlp}}`. 

Alternatively you can pass in your helper just for a given render call. using `myTemplate.render(data, {myHlp: helper})` - and again you can access it as `~myHlp` in the template.

**Comment by mosquito1994** [comment]
Thank you for the answer that I didn't understand the instructions very clearly.
