### ISSUE TITLE
How to use jsrender script template in angular 2 application?

### ISSUE THREAD

**Issue by thangam105** [BorisMoore/jsrender#306]
I have tried jsrender script template <script type="text/x-jsrender"></script> in angular 2 application

Its not working to me 

Please suggestion to me

Regards,
Thangavel E

**Comment by BorisMoore** [comment]
The issues data base is either for bug reports or for feature requests. 

Also, it is not really possible to reply to your question since I have no idea what approach you tried to use for using JsRender templates, and what went wrong. In addition, I  am not an Angular expert, so cannot provide specific help on this at this point...
