### ISSUE TITLE
Uncaugth TypeError: Cannot set property 'tmplName' of undefined

### ISSUE THREAD

**Issue by minias** [BorisMoore/jsrender#310]
Chrome version 57.0.2987.37 beta (64-bit)
jsRender v0.9.83 (Beta)

This code produces a very rare error. ..[850 Line]
In my opinion, the value of the object is likely to not be declared..
If the object is not defined, it is likely to be resolved by handling the exception.

`value.tmplName = name = name || currentName;`
 
![image](https://cloud.githubusercontent.com/assets/4125264/22970593/094880aa-f3b6-11e6-8894-a6998473227d.png)

![image](https://cloud.githubusercontent.com/assets/4125264/22970450/9279c5f6-f3b5-11e6-8c48-97ac3c27902b.png)

**Comment by BorisMoore** [comment]
Can you give more information on what you are doing? Are you using JsRender with jQuery or without. How are you declaring your template? Can you show your code where you call $.templates(...)?

**Comment by minias** [comment]
ok. 
We're using jquery together.
![image](https://cloud.githubusercontent.com/assets/4125264/23009617/59a6f76c-f45a-11e6-9a7b-d624331c6019.png)

The following functions are reproduced and reused as follows :
![image](https://cloud.githubusercontent.com/assets/4125264/23010115/17bed60a-f45d-11e6-979f-5860c9b631d7.png)


Call up the .inject function here.
![image](https://cloud.githubusercontent.com/assets/4125264/23009953/38cefed4-f45c-11e6-9903-e5fc4682cf3f.png)

Do you need more information?

**Comment by BorisMoore** [comment]
What kind of element is being used (with id "major-tmpl") to declare the template. It is not a good idea to use elements other than script blocks as containers for registering templates. Otherwise best to use a string. https://www.jsviews.com/#compiletmpl.

If you do use a container element, then JsRender caches the compiled template. If you then re-access the template by a second call to $.templates("#major-tmpl"), the cached version will be used. But in your case it looks as if the cached copy or the container element have been corrupted. For example the following code will simulate the error condition you are hitting:

```
var tmpl = $.templates("#major-tmpl"); // Compile template

var html = tmpl.render(data); 

$("#major-tmpl").data("jsvTmpl", null); // Remove the cached compile template, to provoke error scenario

var tmpl2 = $.templates("#major-tmpl"); // Try to reaccess and reuse compiled template (Error)

var html2 = tmpl2.render(data); 
```

Is there anything you are doing which might corrupt or modify the element, or  the cached copy of the template?

The following version of JsRender includes a defensive fix for the above scenario. You can test it to see if it successfully resolves your issue. 
[jsrender.zip](https://github.com/BorisMoore/jsrender/files/780941/jsrender.zip)

**Comment by minias** [comment]
@BorisMoore 
Changing to correct version will not result in error.
Thanks for the patch version.  👍

**Comment by BorisMoore** [comment]
Did you figure out why or how that element, or its JsRender data is getting modified/corrupted? What element type are you using as container for the template?

**Comment by minias** [comment]
@BorisMoore  
Even though we should not use the cache intentionally, the previous developers ignored it and applied it to the template. 
I am currently improving the system we use. 
Our final goal will be to remove all libraries that prevent real-time elements from our systems. 
Nevertheless, I am grateful to you for correcting the current issue.

**Comment by BorisMoore** [comment]
OK - thanks for the update. Closing this issue.
