### ISSUE TITLE
Precompile jsrender templates to avoid unsafe-eval

### ISSUE THREAD

**Issue by robbertbrak** [BorisMoore/jsrender#336]
For implementing our Content Security Policy I would like to avoid any code that uses `eval()` or `new Function`, so that I don't have to add `unsafe-eval` to the CSP. However, JsRender uses `new Function` to compile templates. 

Is there a way to avoid this or work around it? Is it on the JsRender roadmap?

Note: I was thinking of solving this by precompiling our templates on the server (something like http://handlebarsjs.com/precompilation.html), so that I only need to render on the client. When I examine the code, it looks like I could make it work by serializing the compiled template (i.e., the result of calling `compileTmpl`), including all its subtemplates, to a JSON-string on the server, putting that in a `<script>` tag and then use that to render.

One of the issues I'm running into with this approach, is that the compiled templates also contain a reference to a `render` function, which is internal to JsRender. I would have to expose it to be able to use it on the client, I think.

**Comment by BorisMoore** [comment]
I will need to work on adding this as a new feature. I'm not sure yet whether to add it to the V1.0 version that is planned soon, or whether to make it post V1.0. But I have a prototype implementation that you could test, and let me know your thoughts.

Here is the prototype (based on my current working version so has some other changes since V0.9.90): 
[jsrender_precompilation_candidate.js.txt](https://github.com/BorisMoore/jsrender/files/1913568/jsrender_precompilation_candidate.js.txt)

Here is how it works.

New API:

    var preCompiled = $.views.preCompile(...);

which does pre-compilation, with eval/new Function calls, with same signature options as $.templates(...): markupString / name, markupString / hash of markupStrings for named templates. 

It returns an object or a hash of *'precompiled template'* objects, which are plain javascript objects, with properties: 
- markup: Markup string, 
- fn: compiled Template function
- tmplName: Name string
- template: Hash of *'precompiled template'* objects for subtemplates

You can also run it without parameters, in a page that has already got any number of registered templates, and it will return the precompiled objects for that page. 

You can run it on the server or in a different time frame, and store the precompiled template objects.

Then at runtime in the browser you can pass exactly the returned object/hash/tree of objects to the normal $.templates method in order to establish the normal template registration, but this will use the pre-compiled functions and will not need to do eval. It will also be faster, and can run on  a page with a a lightweight jsrender.runtime.js with no compilation code, if we make that available. 

    $.templates(preCompiled);

Of course you can hand-optimize the compiled functions, `precompiledOb.fn` that you pass to `$.templates(...)`.

Usage example:

```
var data = {name: "Jo", address: {street: "1st Ave.", zip: "120300"}};

$.templates({
	personTmpl: "Name: {{:name}}<br/> {{include address tmpl='addressTmpl'/}}",
	addressTmpl: {
		markup: "Street: {{:street}} {{include tmpl='zipCode'/}}",
		templates: {zipCode: "Zip code: {{:zip}}"}
	}
});

var preCompiled = $.views.preCompile();
//preCompiled.personTmpl.fn = newPersonTmplFn; // Could replace a function by an optimized version
$.templates({personTmpl: null, addressTmpl: null}); // For  test purposes, unregister templates
$.templates(preCompiled); // Register templates using precompiled objects
var html = $.templates.personTmpl(data);
```

**Comment by robbertbrak** [comment]
That looks very promising, thanks! Since this is not a breaking API change, it would be great if you could put it in the V1 release. But of course, I leave that decision up to you.

I tried the prototype. It works well with toplevel templates, but it seems to break on subtemplates introduced by `{{for}}` and `{{if}}` tags. For example, the following does not render the addresses:

```
var data = {name: "Jo", addresses: [{street: "1st Ave.", zip: "120300"}, {street: "2nd Ave.", zip: '450600'}]};

$.templates({
  personTmpl: "Name: {{:name}}<br/> {{for addresses}}Street: {{:street}}<br/>{{/for}}"
});

var preCompiled = $.views.preCompile();
//preCompiled.personTmpl.fn = newPersonTmplFn; // Could replace a function by an optimized version
$.templates({personTmpl: null, addressTmpl: null}); // For  test purposes, unregister templates
$.templates(preCompiled); // Register templates using precompiled objects
var html = $.templates.personTmpl(data);
```

**Comment by BorisMoore** [comment]
Yes, you are right - the implementation was incomplete. (It was more of a proof of concept).

Here is an update that should work for a range of scenarios: [jsviews.js.txt](https://github.com/BorisMoore/jsrender/files/1917785/jsviews.js.txt).

It will work with both JsRender and with JsViews. So even in JsViews, all calls to new Function can be avoided by precompiling.

One technique for obtaining the compiled object hierarchy that you need to server-render into the page's javascript (or add statically to the HTML page) is to include [`{{jsonview/}}`](http://www.jsviews.com/#samples/tag-controls/jsonview) in a page to render the complete precompiled object hierarchy:

    $.templates("{{jsonview/}}").link("body", $.views.preCompile(tmpl2)); 

You will need this updated jsonview.js, though: [jsonview.js.txt](https://github.com/BorisMoore/jsrender/files/1918186/jsonview.js.txt)

Then  you simply select and copy-paste the rendered object hierarchy to your HTML page and pass is to $.templates() to register the templates:

    $.templates({...});

**Comment by BorisMoore** [comment]
Yes, it was skipping all properties of type function (per previous scenarios it was used for).
So here is an updated jsonview.js and jsonview.css which should render functions too. 

[jsonview.js.txt](https://github.com/BorisMoore/jsrender/files/1922705/jsonview.js.txt)
[jsonview.css.txt](https://github.com/BorisMoore/jsrender/files/1922616/jsonview.css.txt)

But it will need to be used with the corresponding updated jsviews.js, which is here:
[jsviews.js.txt](https://github.com/BorisMoore/jsrender/files/1922708/jsviews.js.txt)

With this version you can still opt in to the previous behavior by setting `{{jsonview ... noFunctions=true .../}}`

**Comment by BorisMoore** [comment]
Hi Robbert, just to let you know that I am working more on this potential feature. Current code is of course not yet working completely (the jsviews.js.txt above) but I will keep you posted here of progress....

**Comment by robbertbrak** [comment]
I'm happy to hear that. Thank you again for the effort you're putting into this!

**Comment by robbertbrak** [comment]
That's too bad, but I understand your decision, now that it turns out to be unfeasible to make it work in the general case. For me personally, however, I think that the special cases in which it _does_ work are sufficient, as I'm only using JsRender and (probably) don't do any of the things that require on-the-fly compilation.

Coming back to my original purpose, which is getting rid of `unsafe-eval` in our Content Security Policy, is there still some way to get there, even if it means that I cannot use the full strength of JsViews / JsRender? For example: exposing just enough of the compilation API to be able to build my own precompilation?

**Comment by BorisMoore** [comment]
I'll try to look into alternatives as some point, but probably not until after getting out the next update (which is overdue).... I'll keep this open now, to track that...

**Comment by BorisMoore** [comment]
Closing for now, but added an After V1? label. I'll consider reopening at some point. (But no promises :) ...)

**Comment by BorisMoore** [comment]
No plan for the moment. . (Although we may re-consider this in the future...). See also the discussion [here](https://github.com/BorisMoore/jsrender/issues/368#issuecomment-1110165455).

**Comment by YannickLafont** [comment]
Hello, do you have any plan to add this feature soon? Should we wait or it won't come out?

**Comment by BorisMoore** [comment]
Unfortunately, following earlier attempts, and associated issues (as discussed earlier in this thread), there is no current plan to provide this feature.

**Comment by anthonyhashemi** [comment]
Hi, I know previously it was decided not to address this issue but I was wondering if anyone who was trying to avoid adding the `unsafe-eval` directive to their CSP config managed to find a workaround? For context, my team is using https://github.com/UniversalViewer/universalviewer for rendering documents, which in turn uses https://github.com/IIIF-Commons/iiif-gallery-component/blob/master/src/index.ts#L180-L195 which uses JSRender as shown.
